<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot0_gazebo</name>
  <version>1.0.0</version>
  <description>Gazebo simulation and arena environment package for robot0</description>
  <maintainer email="66623851+vuquan2005@users.noreply.github.com">vuquan</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>ros_gz_sim</build_depend>

  <exec_depend>robot0_description</exec_depend>
  <exec_depend>robot0_teleop</exec_depend>
  <exec_depend>robot0_vision</exec_depend>
  <exec_depend>robot0_navigation</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
